//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.2
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
namespace ATest.Models {

	[JsonObject(MemberSerialization.OptIn), Table(Name = "configtb")]
	public partial class Configtb {

		[JsonProperty, Column(IsPrimary = true)]
		public Guid Configid { get; set; }

		[JsonProperty, Column(DbType = "text")]
		public string Configdata { get; set; } = string.Empty;

		[JsonProperty]
		public string Configkey { get; set; } = string.Empty;

		[JsonProperty]
		public long Createtime { get; set; }

		[JsonProperty]
		public Guid Gameid { get; set; }

		[JsonProperty]
		public long Lasttime { get; set; }

		/// <summary>
		/// 最大版本号不包含
		/// </summary>
		[JsonProperty]
		public string Maxver { get; set; } = string.Empty;

		/// <summary>
		/// 最小版本号包含
		/// </summary>
		[JsonProperty]
		public string Minver { get; set; } = string.Empty;

		[JsonProperty]
		public int Status { get; set; }

	}

}
