//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.2
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
namespace ATest.Models {

	[JsonObject(MemberSerialization.OptIn), Table(Name = "gamerecomtb")]
	public partial class Gamerecomtb {

		[JsonProperty, Column(IsPrimary = true, IsIdentity = true)]
		public int Id { get; set; }

		[JsonProperty, Column(DbType = "text")]
		public string Desc { get; set; } = string.Empty;

		[JsonProperty]
		public Guid Gameid { get; set; }

		[JsonProperty]
		public string Icon { get; set; } = string.Empty;

		/// <summary>
		/// 唯一标识
		/// </summary>
		[JsonProperty, Column(DbType = "varchar(200)")]
		public string Markid { get; set; } = string.Empty;

		[JsonProperty]
		public Guid Recomgameid { get; set; }

		[JsonProperty]
		public string Recomgamename { get; set; } = string.Empty;

		[JsonProperty]
		public string Url { get; set; } = string.Empty;

	}

}
