//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.2
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
namespace ATest.Models {

	[JsonObject(MemberSerialization.OptIn), Table(Name = "gametb")]
	public partial class Gametb {

		[JsonProperty, Column(IsPrimary = true)]
		public Guid Gameid { get; set; }

		/// <summary>
		/// 4399 渠道密钥
		/// </summary>
		[JsonProperty]
		public string Channel4399secret { get; set; } = string.Empty;

		/// <summary>
		/// 游戏名
		/// </summary>
		[JsonProperty]
		public string Gamename { get; set; } = string.Empty;

		/// <summary>
		/// 游戏密钥
		/// </summary>
		[JsonProperty]
		public string Gamesecret { get; set; } = string.Empty;

		/// <summary>
		/// 现在支付key
		/// </summary>
		[JsonProperty]
		public string Paynowkey { get; set; } = string.Empty;

		/// <summary>
		/// 现在支付密钥
		/// </summary>
		[JsonProperty]
		public string Paynowsecret { get; set; } = string.Empty;

	}

}
