//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.2
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
namespace ATest.Models {

	[JsonObject(MemberSerialization.OptIn), Table(Name = "ordertb")]
	public partial class Ordertb {

		[JsonProperty, Column(IsPrimary = true)]
		public Guid Orderid { get; set; }

		[JsonProperty]
		public DateTime Createtime { get; set; }

		[JsonProperty]
		public Guid Gameid { get; set; }

		[JsonProperty]
		public Guid Goodsid { get; set; }

		/// <summary>
		/// 商品信息 游戏方随意添加
		///  方便判断是什么商品做什么操作最好是加密之后的数据
		/// </summary>
		[JsonProperty]
		public string Goodsinfo { get; set; } = string.Empty;

		/// <summary>
		/// 订单渠道
		///  0: 官方包(买量包)
		///  3: vivo
		///  4: oppo
		///  5: huawei
		///  6: 4399
		///  7: 应用宝
		/// </summary>
		[JsonProperty]
		public int OrderChannel { get; set; }

		/// <summary>
		/// 订单名称
		/// </summary>
		[JsonProperty]
		public string Ordername { get; set; } = string.Empty;

		/// <summary>
		/// 订单价格 可能与商品价格不一样
		///  折扣等因素
		/// </summary>
		[JsonProperty]
		public string OrderPrice { get; set; } = string.Empty;

		/// <summary>
		/// 0:not pay 1:pay 2:pay and use
		/// </summary>
		[JsonProperty]
		public int Orderstatus { get; set; }

		[JsonProperty]
		public Guid Userid { get; set; }

	}

}
