//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.2
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
namespace ATest.Models {

	[JsonObject(MemberSerialization.OptIn), Table(Name = "payrequestlogtb")]
	public partial class Payrequestlogtb {

		[JsonProperty, Column(IsPrimary = true, IsIdentity = true)]
		public int Id { get; set; }

		[JsonProperty]
		public DateTime Createtime { get; set; }

		[JsonProperty, Column(DbType = "text")]
		public string Getdata { get; set; } = string.Empty;

		/// <summary>
		/// 0:send 1:notify
		/// </summary>
		[JsonProperty]
		public int RequestType { get; set; }

		[JsonProperty, Column(DbType = "text")]
		public string Sendbasedata { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "text")]
		public string Senddata { get; set; } = string.Empty;

		[JsonProperty]
		public string Url { get; set; } = string.Empty;

	}

}
