//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.2
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
namespace ATest.Models {

	[JsonObject(MemberSerialization.OptIn), Table(Name = "qiniuuploadstb")]
	public partial class Qiniuuploadstb {

		[JsonProperty, Column(IsPrimary = true, IsIdentity = true)]
		public int Id { get; set; }

		[JsonProperty, Column(DbType = "datetime")]
		public DateTime Createtime { get; set; }

		[JsonProperty, Column(DbType = "varchar(200)")]
		public string Title { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(350)")]
		public string Url { get; set; } = string.Empty;

	}

}
