//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.2
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
namespace ATest.Models {

	[JsonObject(MemberSerialization.OptIn), Table(Name = "redeemtb")]
	public partial class Redeemtb {

		[JsonProperty, Column(IsPrimary = true)]
		public string Redeemid { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime Consumetime { get; set; }

		[JsonProperty]
		public DateTime Createtime { get; set; }

		/// <summary>
		/// 当前已兑换的次数
		/// </summary>
		[JsonProperty]
		public int Currenttimes { get; set; }

		[JsonProperty]
		public Guid Gameid { get; set; }

		[JsonProperty]
		public string Goodsinfo { get; set; } = string.Empty;

		[JsonProperty]
		public int Status { get; set; }

		/// <summary>
		/// 总的兑换次数
		/// </summary>
		[JsonProperty]
		public int Totaltimes { get; set; }

		[JsonProperty]
		public int Type { get; set; }

	}

}
