//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.2
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
namespace ATest.Models {

	[JsonObject(MemberSerialization.OptIn), Table(Name = "usertb")]
	public partial class Usertb {

		[JsonProperty, Column(IsPrimary = true)]
		public Guid Userid { get; set; }

		[JsonProperty]
		public DateTime Createtime { get; set; }

		[JsonProperty]
		public Guid Gameid { get; set; }

		[JsonProperty]
		public string Icon { get; set; } = string.Empty;

		/// <summary>
		/// 唯一标识符
		///  微信：unionid
		///  游客：deviceid
		/// </summary>
		[JsonProperty]
		public string Markid { get; set; } = string.Empty;

		/// <summary>
		/// 来源：0 注册 1 微信 2 qq 3 手机号
		/// </summary>
		[JsonProperty]
		public int Sourcetype { get; set; }

		[JsonProperty]
		public int Status { get; set; }

		[JsonProperty]
		public string Username { get; set; } = string.Empty;

	}

}
